version: "3"

services:
    backend:
        build: .
        restart: unless-stopped
        ports:
            - "8080:8080"
        networks:
            - app
    db:
        image: mysql:8.0.17
        restart: unless-stopped
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: quiz
        volumes:
            - ./db/data/init-mysql.sql:/docker-entrypoint-initdb.d/init.sql:ro
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
        networks:
            - app
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            # - ./:/var/www  # use this is serving static content from FE build
            - ./conf/nginx/:/etc/nginx/conf.d/
            - ./conf/certbot/conf:/etc/letsencrypt
            - ./conf/certbot/www:/var/www/certbot
        depends_on:
            - frontend
            - backend
        networks:
            - app
        # reload configuration and ssl
        command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./conf/certbot/conf:/etc/letsencrypt
            - ./conf/certbot/www:/var/www/certbot
        # automatic ssl cert renewal every 12 hours
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    frontend:
        build: ../quiz-frontend
        restart: unless-stopped
        ports:
            - "3000:3000"
        networks:
            - app

networks:
    app:
        driver: bridge
