version: '3'

services:
    db:
        image: mysql:8.0.17
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: quiz
        volumes:
            - ./db/data:/var/lib/mysql
    app:
        build: .
        ports:
            - "8080:8080"
        links:
            - db
