version: "3"

services:
    backend:
        build: .
        restart: unless-stopped
        ports:
            - "8080:8080"
        networks:
            - app
    db:
        image: mysql:8.0.17
        restart: unless-stopped
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: quiz
        volumes:
            - ./db/data/init-mysql.sql:/docker-entrypoint-initdb.d/init.sql:ro
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
        networks:
            - app
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            # - ./:/var/www  # use this is serving static content from FE build
            - ./conf/nginx/:/etc/nginx/conf.d/
        networks:
            - app
    frontend:
        build: ../quiz-frontend/
        restart: unless-stopped
        ports:
            - "3000:3000"
        networks:
            - app

networks:
    app:
        driver: bridge
